### ISSUE TITLE
jupyter_kite.stdio error(Future can't be used in 'await' expression)

### ISSUE THREAD

**Issue by xiao-xiaoming** [kiteco/issue-tracker#320]
```
[E 01:56:39.851 LabApp] <LspStdIoReader(parent=<LanguageServerSession(language_s
erver=kitels, argv=['C:\\Program Files\\Kite\\kite-lsp.exe'])>)> couldn't enqueu
e message: None
    Traceback (most recent call last):
      File "D:\Anaconda3\lib\site-packages\jupyter_kite\stdio.py", line 90, in r
ead
        message = await self.read_one()
      File "D:\Anaconda3\lib\site-packages\jupyter_kite\stdio.py", line 109, in
read_one
        line = await convert_yielded(self._readline())
    TypeError: object Future can't be used in 'await' expression
```

**Comment by its-dhung** [comment]
1. What version of Python are you using?
2. What is the output of `pip list`?
3. What is the output of `jupyter labextension list`?
