### ISSUE TITLE
Kite extension error for Jupyterlab 

### ISSUE THREAD

**Issue by kptib88** [kiteco/issue-tracker#338]
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

**I'm running Anaconda on Windows 10
Installed kite, jupyter-kite

but I'm getting an error with this line of code

jupyter labextension install "@kiteco/jupyterlab-kite"

The error message is..**

(base) C:\Windows\system32>jupyter labextension install "@kiteco/jupyterlab-kite"
Building jupyterlab assets (build:prod:minimize)
-Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1366, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 263: illegal multibyte sequence
An error occured.
IndexError: list index out of range
See the log file for details:  C:\Users\kptib\AppData\Local\Temp\jupyterlab-debug-wmt0yfvf.log

**When I open the log file.. I have..**

Node v14.7.0

Yarn configuration loaded.
> C:\ProgramData\Anaconda3\npm.CMD pack @kiteco/jupyterlab-kite
npm notice 
npm notice package: @kiteco/jupyterlab-kite@1.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE                                                    
npm notice 707B   style/variables/base.css                                   
npm notice 1.4kB  style/variables/cm-themes.css                              
npm notice 423B   style/console.css                                          
npm notice 1.7kB  style/diagnostics_listing.css                              
npm notice 1.8kB  style/highlight.css                                        
npm notice 567B   style/index.css                                            
npm notice 131B   style/variables/jupyterlab-dark.css                        
npm notice 128B   style/variables/jupyterlab-light.css                       
npm notice 374B   style/logo.css                                             
npm notice 68B    style/statusbar.css                                        
npm notice 68B    src/babel.config.js                                        
npm notice 2.7kB  lib/adapters/codemirror/cm_adapter.js                      
npm notice 2.1kB  lib/adapters/codemirror/cm_adapter.spec.js                 
npm notice 6.7kB  lib/command_manager.js                                     
npm notice 1.8kB  lib/command_manager.spec.js                                
npm notice 1.9kB  lib/adapters/codemirror/features/completion.js             
npm notice 16.7kB lib/adapters/jupyterlab/components/completion.js           
npm notice 10.7kB lib/connection_manager.js                                  
npm notice 4.6kB  lib/connection.js                                          
npm notice 1.4kB  lib/virtual/console.js                                     
npm notice 480B   lib/converter.js                                           
npm notice 4.2kB  lib/extractors/defaults.js                                 
npm notice 5.1kB  lib/magics/defaults.js                                     
npm notice 4.0kB  lib/extractors/defaults.spec.js                            
npm notice 4.2kB  lib/magics/defaults.spec.js                                
npm notice 9.4kB  lib/adapters/codemirror/features/diagnostics_listing.js    
npm notice 14.9kB lib/adapters/codemirror/features/diagnostics.js            
npm notice 10.3kB lib/adapters/codemirror/features/diagnostics.spec.js       
npm notice 21.2kB lib/virtual/document.js                                    
npm notice 8.1kB  lib/virtual/document.spec.js                               
npm notice 6.7kB  lib/virtual/editor.js                                      
npm notice 5.6kB  lib/virtual/editor.spec.js                                 
npm notice 14.1kB lib/adapters/codemirror/feature.js                         
npm notice 10.4kB lib/adapters/codemirror/feature.spec.js                    
npm notice 2.3kB  lib/adapters/jupyterlab/file_editor.js                     
npm notice 1.7kB  lib/virtual/editors/file_editor.js                         
npm notice 2.1kB  lib/adapters/jupyterlab/components/free_tooltip.js         
npm notice 3.6kB  lib/adapters/codemirror/features/highlights.js             
npm notice 7.9kB  lib/adapters/codemirror/features/hover.js                  
npm notice 6.7kB  lib/index.js                                               
npm notice 19.1kB lib/adapters/jupyterlab/jl_adapter.js                      
npm notice 4.9kB  lib/adapters/codemirror/features/jump_to.js                
npm notice 1.4kB  lib/kite_commands.js                                       
npm notice 1.2kB  lib/adapters/jupyterlab/kite_completer.js                  
npm notice 19.4kB lib/adapters/jupyterlab/kite_model.js                      
npm notice 1.9kB  lib/kite_onboarding.js                                     
npm notice 2.8kB  lib/lsp.js                                                 
npm notice 2.2kB  lib/manager.js                                             
npm notice 1.7kB  lib/magics/maps.js                                         
npm notice 5.8kB  lib/adapters/jupyterlab/notebook.js                        
npm notice 9.3kB  lib/virtual/editors/notebook.js                            
npm notice 37B    lib/magics/overrides.js                                    
npm notice 1.1kB  lib/positioning.js                                         
npm notice 2.8kB  lib/positioning.spec.js                                    
npm notice 3.4kB  lib/extractors/regexp.js                                   
npm notice 7.6kB  lib/extractors/regexp.spec.js                              
npm notice 4.3kB  lib/adapters/codemirror/features/rename.js                 
npm notice 1.5kB  lib/adapters/codemirror/features/rename.spec.js            
npm notice 2.7kB  lib/magics/rpy2.js                                         
npm notice 3.9kB  lib/magics/rpy2.spec.js                                    
npm notice 1.7kB  lib/adapters/codemirror/features/selection.js              
npm notice 4.4kB  lib/adapters/codemirror/features/signature.js              
npm notice 4.6kB  lib/adapters/jupyterlab/components/status_model.js         
npm notice 1.6kB  lib/adapters/jupyterlab/components/statusbar.js            
npm notice 6.2kB  lib/adapters/codemirror/testutils.js                       
npm notice 210B   lib/tokens.js                                              
npm notice 33B    lib/extractors/types.js                                    
npm notice 3.4kB  lib/utils.js                                               
npm notice 3.7kB  package.json                                               
npm notice 2.5kB  lib/adapters/codemirror/cm_adapter.js.map                  
npm notice 1.9kB  lib/adapters/codemirror/cm_adapter.spec.js.map             
npm notice 5.5kB  lib/command_manager.js.map                                 
npm notice 1.9kB  lib/command_manager.spec.js.map                            
npm notice 1.3kB  lib/adapters/codemirror/features/completion.js.map         
npm notice 11.7kB lib/adapters/jupyterlab/components/completion.js.map       
npm notice 8.0kB  lib/connection_manager.js.map                              
npm notice 4.1kB  lib/connection.js.map                                      
npm notice 1.7kB  lib/virtual/console.js.map                                 
npm notice 629B   lib/converter.js.map                                       
npm notice 2.9kB  lib/extractors/defaults.js.map                             
npm notice 3.2kB  lib/magics/defaults.js.map                                 
npm notice 3.8kB  lib/extractors/defaults.spec.js.map                        
npm notice 3.4kB  lib/magics/defaults.spec.js.map                            
npm notice 9.2kB  lib/adapters/codemirror/features/diagnostics_listing.js.map
npm notice 10.4kB lib/adapters/codemirror/features/diagnostics.js.map        
npm notice 8.7kB  lib/adapters/codemirror/features/diagnostics.spec.js.map   
npm notice 15.9kB lib/virtual/document.js.map                                
npm notice 6.4kB  lib/virtual/document.spec.js.map                           
npm notice 4.6kB  lib/virtual/editor.js.map                                  
npm notice 4.9kB  lib/virtual/editor.spec.js.map                             
npm notice 11.1kB lib/adapters/codemirror/feature.js.map                     
npm notice 8.0kB  lib/adapters/codemirror/feature.spec.js.map                
npm notice 2.2kB  lib/adapters/jupyterlab/file_editor.js.map                 
npm notice 1.5kB  lib/virtual/editors/file_editor.js.map                     
npm notice 1.8kB  lib/adapters/jupyterlab/components/free_tooltip.js.map     
npm notice 2.9kB  lib/adapters/codemirror/features/highlights.js.map         
npm notice 5.8kB  lib/adapters/codemirror/features/hover.js.map              
npm notice 5.3kB  lib/index.js.map                                           
npm notice 12.9kB lib/adapters/jupyterlab/jl_adapter.js.map                  
npm notice 3.5kB  lib/adapters/codemirror/features/jump_to.js.map            
npm notice 1.3kB  lib/kite_commands.js.map                                   
npm notice 1.0kB  lib/adapters/jupyterlab/kite_completer.js.map              
npm notice 13.5kB lib/adapters/jupyterlab/kite_model.js.map                  
npm notice 1.8kB  lib/kite_onboarding.js.map                                 
npm notice 1.8kB  lib/lsp.js.map                                             
npm notice 2.2kB  lib/manager.js.map                                         
npm notice 1.8kB  lib/magics/maps.js.map                                     
npm notice 4.9kB  lib/adapters/jupyterlab/notebook.js.map                    
npm notice 8.2kB  lib/virtual/editors/notebook.js.map                        
npm notice 120B   lib/magics/overrides.js.map                                
npm notice 1.1kB  lib/positioning.js.map                                     
npm notice 3.8kB  lib/positioning.spec.js.map                                
npm notice 2.8kB  lib/extractors/regexp.js.map                               
npm notice 7.0kB  lib/extractors/regexp.spec.js.map                          
npm notice 3.4kB  lib/adapters/codemirror/features/rename.js.map             
npm notice 1.6kB  lib/adapters/codemirror/features/rename.spec.js.map        
npm notice 2.9kB  lib/magics/rpy2.js.map                                     
npm notice 3.4kB  lib/magics/rpy2.spec.js.map                                
npm notice 1.3kB  lib/adapters/codemirror/features/selection.js.map          
npm notice 3.4kB  lib/adapters/codemirror/features/signature.js.map          
npm notice 3.9kB  lib/adapters/jupyterlab/components/status_model.js.map     
npm notice 1.4kB  lib/adapters/jupyterlab/components/statusbar.js.map        
npm notice 5.7kB  lib/adapters/codemirror/testutils.js.map                   
npm notice 220B   lib/tokens.js.map                                          
npm notice 116B   lib/extractors/types.js.map                                
npm notice 2.8kB  lib/utils.js.map                                           
npm notice 486B   style/icons/kite-logo.svg                                  
npm notice 7.0kB  src/_schema.d.ts                                           
npm notice 886B   lib/adapters/codemirror/cm_adapter.d.ts                    
npm notice 11B    lib/adapters/codemirror/cm_adapter.spec.d.ts               
npm notice 2.3kB  src/adapters/codemirror/cm_adapter.spec.ts                 
npm notice 2.9kB  src/adapters/codemirror/cm_adapter.ts                      
npm notice 3.6kB  lib/command_manager.d.ts                                   
npm notice 11B    lib/command_manager.spec.d.ts                              
npm notice 1.9kB  src/command_manager.spec.ts                                
npm notice 7.7kB  src/command_manager.ts                                     
npm notice 309B   lib/adapters/codemirror/features/completion.d.ts           
npm notice 3.2kB  lib/adapters/jupyterlab/components/completion.d.ts         
npm notice 1.9kB  src/adapters/codemirror/features/completion.ts             
npm notice 17.6kB src/adapters/jupyterlab/components/completion.ts           
npm notice 3.3kB  lib/connection_manager.d.ts                                
npm notice 12.0kB src/connection_manager.ts                                  
npm notice 1.4kB  lib/connection.d.ts                                        
npm notice 5.4kB  src/connection.ts                                          
npm notice 734B   lib/virtual/console.d.ts                                   
npm notice 1.7kB  src/virtual/console.ts                                     
npm notice 497B   lib/converter.d.ts                                         
npm notice 743B   src/converter.ts                                           
npm notice 134B   lib/extractors/defaults.d.ts                               
npm notice 581B   lib/magics/defaults.d.ts                                   
npm notice 11B    lib/extractors/defaults.spec.d.ts                          
npm notice 11B    lib/magics/defaults.spec.d.ts                              
npm notice 3.9kB  src/extractors/defaults.spec.ts                            
npm notice 4.0kB  src/magics/defaults.spec.ts                                
npm notice 3.8kB  src/extractors/defaults.ts                                 
npm notice 4.5kB  src/magics/defaults.ts                                     
npm notice 2.6kB  lib/adapters/codemirror/features/diagnostics_listing.d.ts  
npm notice 1.8kB  lib/adapters/codemirror/features/diagnostics.d.ts          
npm notice 11B    lib/adapters/codemirror/features/diagnostics.spec.d.ts     
npm notice 9.0kB  src/adapters/codemirror/features/diagnostics.spec.ts       
npm notice 14.8kB src/adapters/codemirror/features/diagnostics.ts            
npm notice 8.0kB  lib/virtual/document.d.ts                                  
npm notice 11B    lib/virtual/document.spec.d.ts                             
npm notice 8.0kB  src/virtual/document.spec.ts                               
npm notice 24.3kB src/virtual/document.ts                                    
npm notice 4.4kB  lib/virtual/editor.d.ts                                    
npm notice 11B    lib/virtual/editor.spec.d.ts                               
npm notice 6.0kB  src/virtual/editor.spec.ts                                 
npm notice 8.4kB  src/virtual/editor.ts                                      
npm notice 5.0kB  lib/adapters/codemirror/feature.d.ts                       
npm notice 11B    lib/adapters/codemirror/feature.spec.d.ts                  
npm notice 9.6kB  src/adapters/codemirror/feature.spec.ts                    
npm notice 16.4kB src/adapters/codemirror/feature.ts                         
npm notice 1.8kB  lib/adapters/jupyterlab/file_editor.d.ts                   
npm notice 946B   lib/virtual/editors/file_editor.d.ts                       
npm notice 3.3kB  src/adapters/jupyterlab/file_editor.ts                     
npm notice 2.2kB  src/virtual/editors/file_editor.ts                         
npm notice 785B   lib/adapters/jupyterlab/components/free_tooltip.d.ts       
npm notice 2.4kB  src/adapters/jupyterlab/components/free_tooltip.ts         
npm notice 591B   lib/adapters/codemirror/features/highlights.d.ts           
npm notice 3.4kB  src/adapters/codemirror/features/highlights.ts             
npm notice 1.3kB  lib/adapters/codemirror/features/hover.d.ts                
npm notice 8.1kB  src/adapters/codemirror/features/hover.ts                  
npm notice 257B   lib/index.d.ts                                             
npm notice 6.8kB  src/index.ts                                               
npm notice 6.9kB  lib/adapters/jupyterlab/jl_adapter.d.ts                    
npm notice 21.0kB src/adapters/jupyterlab/jl_adapter.ts                      
npm notice 599B   lib/adapters/codemirror/features/jump_to.d.ts              
npm notice 4.6kB  src/adapters/codemirror/features/jump_to.ts                
npm notice 544B   lib/kite_commands.d.ts                                     
npm notice 1.5kB  src/kite_commands.ts                                       
npm notice 635B   lib/adapters/jupyterlab/kite_completer.d.ts                
npm notice 1.2kB  src/adapters/jupyterlab/kite_completer.ts                  
npm notice 5.5kB  lib/adapters/jupyterlab/kite_model.d.ts                    
npm notice 19.0kB src/adapters/jupyterlab/kite_model.ts                      
npm notice 781B   lib/kite_onboarding.d.ts                                   
npm notice 2.4kB  src/kite_onboarding.ts                                     
npm notice 1.7kB  lib/lsp.d.ts                                               
npm notice 2.2kB  src/lsp.ts                                                 
npm notice 642B   lib/manager.d.ts                                           
npm notice 2.3kB  src/manager.ts                                             
npm notice 1.1kB  lib/magics/maps.d.ts                                       
npm notice 2.1kB  src/magics/maps.ts                                         
npm notice 2.3kB  lib/adapters/jupyterlab/notebook.d.ts                      
npm notice 3.7kB  lib/virtual/editors/notebook.d.ts                          
npm notice 7.0kB  src/adapters/jupyterlab/notebook.ts                        
npm notice 11.2kB src/virtual/editors/notebook.ts                            
npm notice 532B   lib/magics/overrides.d.ts                                  
npm notice 516B   src/magics/overrides.ts                                    
npm notice 856B   lib/positioning.d.ts                                       
npm notice 11B    lib/positioning.spec.d.ts                                  
npm notice 2.6kB  src/positioning.spec.ts                                    
npm notice 1.6kB  src/positioning.ts                                         
npm notice 2.6kB  lib/extractors/regexp.d.ts                                 
npm notice 11B    lib/extractors/regexp.spec.d.ts                            
npm notice 6.8kB  src/extractors/regexp.spec.ts                              
npm notice 5.5kB  src/extractors/regexp.ts                                   
npm notice 350B   lib/adapters/codemirror/features/rename.d.ts               
npm notice 11B    lib/adapters/codemirror/features/rename.spec.d.ts          
npm notice 1.4kB  src/adapters/codemirror/features/rename.spec.ts            
npm notice 4.4kB  src/adapters/codemirror/features/rename.ts                 
npm notice 707B   lib/magics/rpy2.d.ts                                       
npm notice 11B    lib/magics/rpy2.spec.d.ts                                  
npm notice 3.6kB  src/magics/rpy2.spec.ts                                    
npm notice 2.5kB  src/magics/rpy2.ts                                         
npm notice 223B   lib/adapters/codemirror/features/selection.d.ts            
npm notice 1.5kB  src/adapters/codemirror/features/selection.ts              
npm notice 934B   lib/adapters/codemirror/features/signature.d.ts            
npm notice 4.4kB  src/adapters/codemirror/features/signature.ts              
npm notice 1.4kB  lib/adapters/jupyterlab/components/status_model.d.ts       
npm notice 4.8kB  src/adapters/jupyterlab/components/status_model.ts         
npm notice 466B   lib/adapters/jupyterlab/components/statusbar.d.ts          
npm notice 74B    src/svg.d.ts                                               
npm notice 3.4kB  lib/adapters/codemirror/testutils.d.ts                     
npm notice 7.5kB  src/adapters/codemirror/testutils.ts                       
npm notice 879B   lib/tokens.d.ts                                            
npm notice 845B   src/tokens.ts                                              
npm notice 2.3kB  lib/extractors/types.d.ts                                  
npm notice 2.3kB  src/extractors/types.ts                                    
npm notice 166B   src/typings.d.ts                                           
npm notice 1.3kB  lib/utils.d.ts                                             
npm notice 3.3kB  src/utils.ts                                               
npm notice 10.0kB src/adapters/codemirror/features/diagnostics_listing.tsx   
npm notice 1.5kB  src/adapters/jupyterlab/components/statusbar.tsx           
npm notice === Tarball Details === 
npm notice name:          @kiteco/jupyterlab-kite                 
npm notice version:       1.0.0                                   
npm notice filename:      kiteco-jupyterlab-kite-1.0.0.tgz        
npm notice package size:  215.4 kB                                
npm notice unpacked size: 995.0 kB                                
npm notice shasum:        ac955f31cd89fb92b86370dcccb5a7ac8b71b6dd
npm notice integrity:     sha512-elFk7MuZ27Swf[...]DYchnKWXGqP+A==
npm notice total files:   245                                     
npm notice 
kiteco-jupyterlab-kite-1.0.0.tgz

Node v14.7.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.41s.

> node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
Done in 0.29s.

> node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 657, in build
    ret = self._run(['node', YARN_PATH, 'run', command], cwd=staging)

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1752, in _run
    return proc.wait()

  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 107, in wait
    out, _ = proc.communicate(timeout=.1)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1416, in _communicate
    stdout = stdout[0]

IndexError: list index out of range

Exiting application: jupyter

**PIP list**

Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
argh                               0.26.2
asn1crypto                         1.3.0
astroid                            2.4.2
astropy                            4.0.1.post1
atomicwrites                       1.4.0
attrs                              19.3.0
autopep8                           1.5.3
Babel                              2.8.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.1.7
beautifulsoup4                     4.9.1
bitarray                           1.4.0
bkcharts                           0.2
bleach                             3.1.5
bokeh                              2.1.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
certifi                            2020.6.20
cffi                               1.14.0
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.5.0
clyent                             1.2.2
colorama                           0.4.3
comtypes                           1.1.7
conda                              4.8.3
conda-build                        3.18.11
conda-package-handling             1.7.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       2.9.2
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.10.1
dask                               2.20.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.20.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.3
Flask                              1.1.2
fsspec                             0.7.4
future                             0.18.2
gevent                             20.6.2
glob2                              0.7
gmpy2                              2.0.8
greenlet                           0.4.16
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
intervaltree                       3.0.2
ipykernel                          5.3.2
ipython                            7.16.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
joblib                             0.16.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.1.0
jupyter-core                       4.6.3
jupyter-kite                       1.0.0
jupyterlab                         2.1.5
jupyterlab-server                  1.2.0
keyring                            21.2.1
kiwisolver                         1.2.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lxml                               4.5.2
MarkupSafe                         1.1.1
matplotlib                         3.2.2
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.4.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.7
networkx                           2.4
nltk                               3.5
nose                               1.3.7
notebook                           6.0.3
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.18.5
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.4
packaging                          20.4
pandas                             1.0.5
pandocfilters                      1.4.2
paramiko                           2.7.1
parso                              0.7.0
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.1.1
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.5
psutil                             5.7.0
py                                 1.9.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.5
pydocstyle                         5.0.2
pyflakes                           2.2.0
Pygments                           2.6.1
pylint                             2.5.3
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.16.0
PySocks                            1.7.1
pytest                             5.4.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.34.1
pytz                               2020.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.1
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.5
QtPy                               1.9.0
regex                              2020.6.8
requests                           2.24.0
rope                               0.17.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.23.1
scipy                              1.5.0
seaborn                            0.10.1
Send2Trash                         1.5.0
setuptools                         49.2.0.post20200714
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.1.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.3
spyder                             4.1.4
spyder-kernels                     1.9.2
SQLAlchemy                         1.3.18
statsmodels                        0.11.1
sympy                              1.6.1
tables                             3.6.1
tblib                              1.6.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.47.0
traitlets                          4.3.3
typing-extensions                  3.7.4.2
ujson                              1.35
unicodecsv                         0.14.1
urllib3                            1.25.9
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.2.9
xlwings                            0.19.5
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     4.7.1v

**Jupyter labextension list:**

JupyterLab v2.1.5
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
        @kiteco/jupyterlab-kite v1.0.0 enabled  ok

**Screenshots**

**Comment by its-dhung** [comment]
This might be solved by specifying the character encoding in the relevant files.

@kptib88 in the meantime, you can try installing Kite again if you change your system to use UTF-8 by default.
