### ISSUE TITLE
Enabling  jupyter lab kite: Validation failed: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ThamuMnyulwa** [kiteco/issue-tracker#608]
> Can you try running
> 
> ```
> jupyter server extension enable jupyter_kite
> ```
> 
> Also, ensure you have the Kite Engine process active.

I am trying to enable the kite server using jupyter lab 3.0.6. The enabling process is giving me an error as shown below.

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter server extension enable jupyter_kite
Enabling: jupyter_kite
- Writing config: /usr/etc/jupyter
    - Validating jupyter_kite...
      jupyter_kite 2.0.2 <font color="#4E9A06">OK</font>
     <font color="#CC0000"> X</font> Validation failed: [Errno 13] Permission denied: &apos;/usr/etc&apos;
</pre>

How can I resolve this issue?
_Originally posted by @ThamuMnyulwa in https://github.com/kiteco/issue-tracker/issues/601#issuecomment-789431533_

**Comment by ThamuMnyulwa** [comment]
When I run jupyter lab I get this error message:
![build1](https://user-images.githubusercontent.com/43708808/110204819-cf5e2f00-7e7d-11eb-916a-befe619b8ecd.png)

After I try to build I get this message:
![build2](https://user-images.githubusercontent.com/43708808/110204828-d38a4c80-7e7d-11eb-80b3-50a3faa9e972.png)

I followed the instructions and tried to build it in the terminal. I get an error message then go and look at the log file which is below.

![build3](https://user-images.githubusercontent.com/43708808/110204850-f61c6580-7e7d-11eb-8b7a-a4a451bd898f.png)

The log file then looks like this:

[]([]([LabBuildApp] Building in /home/thamu/.local/share/jupyter/lab
[LabBuildApp] Node v15.6.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] WARNING | The extension "@jupyter-widgets/jupyterlab-manager" is outdated.

[LabBuildApp] > node /home/thamu/.local/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning kite > coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning kite > selenium-launcher > request@2.9.203: request has been deprecated, see https://github.com/request/request/issues/3142
warning kite > zombie > request@2.10.0: request has been deprecated, see https://github.com/request/request/issues/3142
warning kite > cukestall > cucumber@0.2.21: The npm package has moved to @cucumber/cucumber
warning kite > cukestall > cucumber > coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning kite > cukestall > ejs@0.6.1: Critical security bugs fixed in 2.5.5
warning kite > zombie > tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning kite > cukestall > cucumber > jasmine-node@1.0.26: jasmine-node 1.x & 2.x are deprecated, with known vulnerability in jasmine-growl-reporter pre-2.0.0
warning kite > cukestall > cucumber > jasmine-node > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning kite > zombie > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning kite > zombie > html5 > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning kite > cukestall > express@2.5.9: express 2.x series is deprecated
warning kite > cukestall > cucumber > mkdirp@0.3.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning kite > cukestall > express > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning kite > cukestall > cucumber > connect@2.3.2: connect 2.x series is deprecated
warning kite > cukestall > express > connect@1.9.2: connect 1.x series is deprecated
warning kite > zombie > html5 > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning kite > cukestall > browserify > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning kite > zombie > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning kite > cukestall > cucumber > rimraf > graceful-fs@1.1.14: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning kite > cukestall > express > connect > formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
warning kite > cukestall > browserify > buffer-browserify@0.0.5: Package not maintained. Recent browserify uses https://github.com/feross/buffer
warning kite > cukestall > browserify > deputy > mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[3/5] Fetching packages...
warning vscode-languageclient@5.2.1: The engine "vscode" appears to be invalid.
error cucumber@0.2.21: The engine "node" is incompatible with this module. Expected version "0.6 || 0.7 || 0.8". Got "15.6.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/thamu/.local/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home/thamu/.local/lib/python3.8/site-packages/jupyterlab/labapp.py", line 168, in start
    raise e

[LabBuildApp]   File "/home/thamu/.local/lib/python3.8/site-packages/jupyterlab/labapp.py", line 164, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/home/thamu/.local/lib/python3.8/site-packages/jupyterlab/commands.py", line 463, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/home/thamu/.local/lib/python3.8/site-packages/jupyterlab/commands.py", line 663, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab))

**Comment by edzkite** [comment]
Hi @ThamuMnyulwa, I'd advise you to go with the guidance given [here](https://github.com/jupyterlab/jupyterlab/issues/9906#issuecomment-792660791). If you continue to experience issues with the Kite plugin specifically, please let us know.

**Comment by Absolute7070** [comment]
> > Can you try running
> > ```
> > jupyter server extension enable jupyter_kite
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, ensure you have the Kite Engine process active.
> 
> I am trying to enable the kite server using jupyter lab 3.0.6. The enabling process is giving me an error as shown below.
> 
> thamu@thamu-PC:~$ jupyter server extension enable jupyter_kite
> Enabling: jupyter_kite
> - Writing config: /usr/etc/jupyter
>     - Validating jupyter_kite...
>       jupyter_kite 2.0.2 OK
>       X Validation failed: [Errno 13] Permission denied: '/usr/etc'
> How can I resolve this issue? _Originally posted by @ThamuMnyulwa in [#601 (comment)](https://github.com/kiteco/issue-tracker/issues/601#issuecomment-789431533)_

I encountered the same problem. But then I moved all the permission from the folder where the "Validation failed" occured using:
`sudo chmod 777 [folder_name]` 
or as in your case 
`sudo chmod 777 etc`


Then I opened the jupyter lab from the terminal and now kite-plugin works fine. 

I do not know what kind of consequences this action will have in the future having removed all the permission from the folder.

**Comment by Absolute7070** [comment]
> 

I mean after you have removed the permission, you should run again the following code:
`jupyter server extension enable jupyter_kite`
