### ISSUE TITLE
Kite isnt installing on Atom or Spyder

### ISSUE THREAD

**Issue by Wizards-god** [kiteco/issue-tracker#825]
Spyder recently removed support for Kite, is there any other way to get Kite working on Spyder?
Spyder isn't that useful without Kite, so I really want Kite to work on Sypder.

The atom package isn't installing and gives me this error:
(node:12832) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

(node:16396) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
npm ERR! code E400
npm ERR! 400 Bad Request - GET https://www.atom.io/api/packages/kite/versions/0.206.0/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\parja\.atom\.apm\_logs\2022-04-05T03_39_23_919Z-debug.log
[2022-04-05T03_39_23_919Z-debug.log](https://github.com/kiteco/issue-tracker/files/8414657/2022-04-05T03_39_23_919Z-debug.log)

I visited the GitHub page for the atom plugin(https://github.com/kiteco/atom-plugin), but that repo has probably been deleted.
Is there any other manual way to install Kite for Atom?

I have tried installing the Atom plugin from the Kite-Copilot app, but that also gives me an error:
Failed to install Atom at path C:\Users\parja\AppData\Local\atom\app-1.60.0\atom.exe
error running C:\Users\parja\AppData\Local\atom\app-1.60.0\apm "install kite": exec: "C:\\Users\\parja\\AppData\\Local\\atom\\app-1.60.0\\apm": file does not exist

**Comment by CyberCodeInfinity** [comment]
i'm having the exact problem for Atom and Spyder

**Comment by bt-** [comment]
I am having the same issue trying to install the Kite plugin for Atom as well. 
I don't get this line of the error, but the rest is the same:
`(node:16396) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections `
I also tried installing from the Kite copilot app, which gave me this error:
`Failed to install Atom at path /usr/bin/atom
error running /usr/bin/apm "install kite": exit status 1`
Here is the error log from Atom:
```
0 info it worked if it ends with ok
  2 1 verbose cli [
  3 1 verbose cli   '/usr/share/atom/resources/app/apm/bin/node',
  4 1 verbose cli   '/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js',
  5 1 verbose cli   '--globalconfig',
  6 1 verbose cli   '/home/ben/.atom/.apm/.apmrc',
  7 1 verbose cli   '--userconfig',
  8 1 verbose cli   '/home/ben/.atom/.apmrc',
  9 1 verbose cli   'install',
 10 1 verbose cli   'https://www.atom.io/api/packages/kite/versions/0.206.0/tarball',
 11 1 verbose cli   '--target=9.4.4',
 12 1 verbose cli   '--disturl=https://atom.io/download/electron',
 13 1 verbose cli   '--arch=x64',
 14 1 verbose cli   '--global-style'
 15 1 verbose cli ]
 16 2 info using npm@6.14.13
 17 3 info using node@v12.14.1
 18 4 verbose npm-session d3bc031caa748ca7
 19 5 silly install loadCurrentTree
 20 6 silly install readLocalPackageData
 21 7 http fetch GET 400 https://www.atom.io/api/packages/kite/versions/0.206.0/tarball 450ms
 22 8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/kite/versions/0.206.0/tarball 400 Bad Request - GET https://www.atom.io/api/packages/kite/versions/0.206.0/tarball
 23 9 timing stage:rollbackFailedOptional Completed in 0ms
 24 10 timing stage:runTopLevelLifecycles Completed in 471ms
 25 11 verbose stack Error: 400 Bad Request - GET https://www.atom.io/api/packages/kite/versions/0.206.0/tarball
 26 11 verbose stack     at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
 27 11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
 28 12 verbose statusCode 400
 29 13 verbose pkgid https://www.atom.io/api/packages/kite/versions/0.206.0/tarball
 30 14 verbose cwd /tmp/apm-install-dir-2022324-3324298-ej6onw.anijt
 31 15 verbose Linux 5.13.0-7620-generic
 32 16 verbose argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/ben/.atom/.apm/.apmrc" "--userconfig" "/home/be    n/.atom/.apmrc" "install" "https://www.atom.io/api/packages/kite/versions/0.206.0/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
 33 17 verbose node v12.14.1
 34 18 verbose npm  v6.14.13
 35 19 error code E400
 36 20 error 400 Bad Request - GET https://www.atom.io/api/packages/kite/versions/0.206.0/tarball
 37 21 verbose exit [ 1, true ]

```

**Comment by Wizards-god** [comment]
Is no one trying to solve this issue from the kite team?

**Comment by Wizards-god** [comment]
It has been close to a month and yet no one has responded with an answer

**Comment by lazyninja007** [comment]
It's the 400 error.  The https://www.atom.io/api/packages/kite/versions/0.206.0/tarball is producing an error.  It can't get the package and instead shows "{"message":"Repository inaccessible"}".
I think the permissions to that file need to be made public.  Just my 2 cents.

**Comment by AmirTlinov** [comment]
i have the same
